# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: argocd
#   namespace: infra-tools
# spec:
#   project: default
#   source:
#     repoURL: "https://github.com/sersim33/goit-argo.git"
#     path: "namespaces"
#     targetRevision: main
#     helm:
#       valueFiles:
#         - values/argocd-values.yaml  # або inline values
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: infra-tools
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true


apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: infra-tools       # Namespace, де встановлено ArgoCD
spec:
  project: default
  source:
    repoURL: "https://github.com/sersim33/goit-argo.git"  # твій репозиторій
    path: "."                  # чарт знаходиться в корені репо (якщо окремий чарт, вкажи папку чарта)
    targetRevision: main       # гілка репо
    helm:
      valueFiles:
        - values/argocd-values.yaml  # overrides для Helm чарта
  destination:
    server: https://kubernetes.default.svc
    namespace: infra-tools     # namespace, куди буде деплоїтися ArgoCD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
